library(shiny)
library(shinydashboard)
library(shinymanager)
library(tidyverse)
library(rjson)
library(readxl)
source("functions.R")
source("shiny_template.R")
source("create_data.R")
credentials <- read_xlsx(path = "config/credentials.xlsx")
climatic_shiny()